title: Mercari Bulk Relist
description: >-
  Bulk relist your Mercari listings in one click. The fastest mercari relisting tool
  for sellers who want to boost sales without wasting hours manually relisting items.
  Mercari bulk relist, mercari seller tools, bulk relist mercari.
url: "https://raymondreddingtonadmin.github.io"
baseurl: "/mercaribulkrelist.com"

markdown: kramdown
permalink: /blog/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
